animal = '     chanchito    feliz    '
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.rstrip())
print(animal.lstrip())
print(animal.find('cH'))
print(animal.replace('ch' , 'j'))
print('fe' in animal)
print('x' in animal)